estagios/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    InstituicaoEnsinoViewSet, ParteConcedenteViewSet, EstagiarioViewSet, ContratoViewSet, RescisaoViewSet,
    AgenteIntegracaoViewSet, CandidatoViewSet, TipoEventoViewSet, LancamentoViewSet, ReciboViewSet, get_contrato_data,
    ReciboRescisaoViewSet, ContratoSocialViewSet, AditivoViewSet, CriterioExclusaoViewSet, ContratoAceiteViewSet
)

router = DefaultRouter()
router.register('instituicoes', InstituicaoEnsinoViewSet)
router.register('empresa', ParteConcedenteViewSet)
router.register('estagiarios', EstagiarioViewSet)
router.register('contratos', ContratoViewSet)
router.register('rescisoes', RescisaoViewSet)
router.register('agentes-integradores', AgenteIntegracaoViewSet)
router.register(r'candidatos', CandidatoViewSet)
router.register(r'tipos-eventos', TipoEventoViewSet, basename='tipoevento')
router.register(r'Lancamentos', LancamentoViewSet, basename='lancamento')
router.register(r'recibos', ReciboViewSet, basename='recibo')
router.register(r'recibo_rescisao', ReciboRescisaoViewSet, basename='recibo-rescisao')
router.register(r'contrato_social', ContratoSocialViewSet, basename='contrato-social')
router.register(r'aditivo', AditivoViewSet, basename='aditivo')
router.register(r'criterios-exclusao', CriterioExclusaoViewSet, basename='criterios-exclusao')
router.register(r'contratos-aceite', ContratoAceiteViewSet, basename='contrato-aceite')

urlpatterns = [
    path('', include(router.urls)),
    path('get-contrato-data/<int:contrato_id>/', get_contrato_data, name='get_contrato_data'),
]

gerador_docs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from django.views.static import serve


schema_view = get_schema_view(
   openapi.Info(
      title="API Geração de PDFs",
      default_version='v1',
      description="Geração de forms de recrutamento com PDF, geração de contrato e rescisão com PDF, além do CRUD de "
                  "candidatos, estagiários, empresas, instituições de ensino e agentes integradores",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contato@sollenco.com.br"),
      license=openapi.License(name="BSD License"),
   ),
   public=False,
   permission_classes=(permissions.IsAdminUser,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('estagios.urls')),
    path('', include('estagios.web_urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

# Em produção, o seu servidor web deve ser configurado para servir os arquivos da pasta MEDIA_ROOT.
# if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),
]

admin.site.site_header = 'Painel de Controle de Candidatos Ellenco Estágios'

admin.site.index_title = 'Bem vindo ao painel de cadastro'

estagios/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from rest_framework.exceptions import ValidationError
from unidecode import unidecode
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
from decimal import Decimal, ROUND_HALF_UP
import re
from unicodedata import normalize


# null para o banco, blank para forms e admin

class InstituicaoEnsino(models.Model):
    razao_social = models.CharField(max_length=250)
    cnpj = models.CharField(max_length=18, unique=True)
    endereco = models.CharField(max_length=250)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=9)
    representante_legal = models.CharField(max_length=100)
    telefone = models.CharField(max_length=15)
    email = models.EmailField()

    class Meta:
        verbose_name = 'Instituição de Ensino'
        verbose_name_plural = 'Instituições de Ensino'

    def __str__(self):
        return self.razao_social


class ParteConcedente(models.Model):
    class Documentos(models.TextChoices):
        CPF = 'C', 'CPF'
        RG = 'R', 'RG'

    nome = models.CharField(max_length=250, null=True, blank=True)
    razao_social = models.CharField(max_length=250, null=True, blank=True)
    endereco = models.CharField(max_length=250)
    bairro = models.CharField(max_length=100)
    local_trabalho = models.CharField(max_length=100, null=True, blank=True)
    estado = models.CharField(max_length=2)
    cnpj = models.CharField(max_length=18, unique=True)
    representante_legal = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    cep = models.CharField(max_length=9)
    telefone = models.CharField(max_length=15)
    email = models.EmailField()
    ramo_atividade = models.CharField(max_length=200, null=True, verbose_name='Ramo de atividade')

    class Meta:
        verbose_name = 'Parte Concedente'
        verbose_name_plural = 'Partes Concedentes'

    def __str__(self):
        if self.nome:
            return self.nome
        return self.razao_social


class DetalhesParteConcedente(models.Model):
    parte_concedente = models.ForeignKey(ParteConcedente, on_delete=models.PROTECT, related_name='detalhes')
    dia_pagamento_estagiario = models.IntegerField(null=True, blank=True)
    dia_cobranca_agencia = models.IntegerField(null=True, blank=True)
    dia_fechamento = models.IntegerField(null=True, blank=True)
    mensalidade_contrato = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True)
    taxa_cliente = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True)


class ContratoSocial(models.Model):
    # Informações adicionais da Parte Concedente para a criação do contrato social
    parte_concedente = models.ForeignKey(ParteConcedente, on_delete=models.PROTECT, related_name='adicionais')
    nome_dono = models.CharField(max_length=100, null=True, blank=True, verbose_name='Nome do(a) dono(a)')
    documentos_dono = models.CharField(verbose_name='CPF do(a) dono(a)', null=True, unique=True, blank=True)
    nome_socio = models.CharField(max_length=100, null=True, blank=True, verbose_name='Nome do(a) sócio(a)')
    documentos_socio = models.CharField(verbose_name='CPF do(a) sócio(a)', null=True, unique=True, blank=True)
    nome_resp_rh = models.CharField(max_length=100, verbose_name='Nome do(a) responsável do RH')
    numero_resp_rh = models.CharField(max_length=11, help_text='Número do telefone com DDD e sem traços',
         verbose_name='Número do(a) responsável do RH')
    email_resp_rh = models.EmailField(verbose_name='Email do(a) responsável do RH')
    nome_resp_estagio = models.CharField(max_length=100, verbose_name='Nome do(a) responsável do estágio')
    data_cadastro = models.DateField(auto_now_add=True, null=True, blank=True)

    class Meta:
        verbose_name = 'Contrato Empresa'
        verbose_name_plural = 'Contratos para Empresas'

    def __str__(self):
        return f'Contrato_Social_{self.parte_concedente.razao_social}'


class Aditivo(models.Model):
    contrato_social = models.ForeignKey(ContratoSocial, on_delete=models.PROTECT, related_name='contrato_social')
    data_cadastro = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Aditivo Contratual'
        verbose_name_plural = 'Aditivos Contratuais'

    def __str__(self):
        concedente = self.contrato_social.parte_concedente

        identificador = concedente.razao_social or concedente.nome

        return f'Aditivo_{identificador}'


class CriterioExclusao(models.Model):
    criterio = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Critério de Exclusão'
        verbose_name_plural = 'Critérios de Exclusão'

    def __str__(self):
        return self.criterio


class Candidato(models.Model):
    class AnosSemestres(models.TextChoices):
        PRIMEIRO_ANO = '1A', '1° Ano'
        SEGUNDO_ANO = '2A', '2° Ano'
        TERCEIRO_ANO = '3A', '3° Ano'
        QUARTO_ANO = '4A', '4° Ano'
        PRIMEIRO_SEMESTRE = '1S', '1° Semestre'
        SEGUNDO_SEMESTRE = '2S', '2° Semestre'
        TERCEIRO_SEMESTRE = '3S', '3° Semestre'
        QUARTO_SEMESTRE = '4S', '4° Semestre'
        QUINTO_SEMESTRE = '5S', '5° Semestre'
        SEXTO_SEMESTRE = '6S', '6° Semestre'
        SETIMO_SEMESTRE = '7S', '7° Semestre'
        OITAVO_SEMESTRE = '8S', '8° Semestre'
        NONO_SEMESTRE = '9S', '9° Semestre'
        DECIMO_SEMESTRE = '1OS', '10° Semestre'
        DECIMO_PRIMEIRO_SEMESTRE = '11S', '11° Semestre'
        DECIMO_SEGUNDO_SEMESTRE = '12S', '12° Semestre'

    class EstadosCivis(models.TextChoices):
        SOLTEIRO = 'S', 'Solteiro(a)'
        CASADO = 'C', 'Casado(a)'
        DIVORCIADO = 'D', 'Divorciado(a)'
        VIUVO = 'V', 'Viúvo(a)'

    class Escolaridades(models.TextChoices):
        ENSINO_MEDIO = 'EM', 'Ensino Médio'
        ENSINO_MEDIO_TECNICO = 'EMT', 'Ensino Médio Técnico'
        ENSINO_SUPERIOR_INCOMPLETO = 'ESI', 'Ensino Superior Incompleto'
        ENSINO_SUPERIOR = 'ES', 'Ensino Superior'
        EDUCACAO_JOVEM_ADULTO = 'EJA', 'Educação de Jovens e Adultos'

    class Periodos(models.TextChoices):
        MANHA = 'M', 'Manhã'
        TARDE = 'T', 'Tarde'
        NOITE = 'N', 'Noite'
        INTEGRAL = 'I', 'Integral'
        EAD = 'E', 'EAD'

    class ValeTransporte(models.TextChoices):
        TOP = 'T', 'Top'
        CIDADAO = 'C', 'Cidadão'
        ESTUDANTE = 'E', 'Estudante'
        NAO_TEM = 'NT', 'Não tem'

    class Trabalhos(models.TextChoices):
        COM_REGISTRO = 'CR', 'Sim, com registro (CLT)'
        SEM_REGISTRO = 'SR', 'Sim, sem registro'
        NAO = 'N', 'Não'
        FREELANCER = 'F', 'Freelancer'
        ESTAGIO = 'E', 'Estágio'

    class Microsoft_365(models.TextChoices):
        SEM_CONHECIMENTO = 'SC', 'Sem conhecimento'
        BASICO = 'B', 'Básico'
        INTERMEDIARIO = 'I', 'Intermediário'
        AVANCADO = 'A', 'Avançado'

    class Habilitacoes(models.TextChoices):
        NP = 'NP', 'Não possui'
        A = 'A', 'Categoria A'
        B = 'B', 'Categoria B'
        C = 'C', 'Categoria C'
        D = 'D', 'Categoria D'
        E = 'E', 'Categoria E'
        AB = 'AB', 'Categorias A e B'

    class PCD(models.TextChoices):
        SIM = 'S', 'Sim'
        NAO = 'N', 'Não'
        PREFIRO_NAO_RESPONDER = 'PNR', 'Prefiro não responder'

    class Medicamento(models.TextChoices):
        SIM = 'S', 'Sim'
        NAO = 'N', 'Não'

    class Alergia(models.TextChoices):
        SIM = 'S', 'Sim'
        NAO = 'N', 'Não'

    class ProblemaSaude(models.TextChoices):
        SIM = 'S', 'Sim'
        NAO = 'N', 'Não'

    # --- DADOS PESSOAIS ---
    nome = models.CharField(max_length=100)
    sexo = models.CharField(max_length=50)
    rg = models.CharField(max_length=12, unique=True, blank=True, verbose_name='RG',
                          help_text='Somente números, campo não necessário caso você tenha o CIN', null=True)
    anexar_rg = models.FileField(
        verbose_name='Anexar RG',
        upload_to='documentos_candidatos/rg/%Y%/%m/%d/', null=True, blank=True)
    cpf = models.CharField(max_length=14, unique=True, blank=True, verbose_name='CPF', help_text='Somente números')
    anexar_cpf = models.FileField(
        verbose_name='Anexar CPF',
        upload_to='documentos_candidatos/cpf/%Y%/%m/%d/', null=True, blank=True)
    data_nascimento = models.DateField(verbose_name='Data de Nascimento')
    estado_civil = models.CharField(max_length=1, choices=EstadosCivis.choices)
    tem_filhos = models.BooleanField(help_text='Tem filhos?', default=False)
    filhos_detalhes = models.CharField(help_text='Quais as idades?', max_length=150, null=True, blank=True)
    celular = models.CharField(max_length=11, unique=True, help_text='11911112222')
    celular2 = models.CharField(max_length=11, unique=True, help_text='Opcional', null=True, blank=True)
    email = models.EmailField()
    rede_social = models.CharField(max_length=100, null=True, blank=True, help_text='Instagram ou Facebook')
    cep = models.CharField(max_length=9, null=True, blank=True, help_text='00000-000', verbose_name='CEP')
    endereco = models.CharField(max_length=200, verbose_name='Endereço')
    numero = models.CharField(max_length=10, verbose_name='Número')
    complemento = models.CharField(max_length=50, null=True, blank=True)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=2)

    # --- INFORMAÇÕES ADICIONAIS ---
    habilitacao = models.CharField(max_length=2, choices=Habilitacoes.choices, verbose_name='Habilitação')
    fumante = models.BooleanField(help_text='É fumante?', default=False)
    religiao = models.CharField(
        max_length=100, null=True, blank=True, help_text='Possui alguma religião? Se sim, qual?', verbose_name='Religião')

estagios/forms.py
from django import forms
from .models import Contrato, Rescisao


class ContratoForm(forms.ModelForm):
    class Meta:
        model = Contrato
        fields = '__all__'

        widgets = {
            'data_inicio': forms.DateInput(attrs={'type': 'date'}),
            'data_termino_prevista': forms.DateInput(attrs={'type': 'date'}),
        }

estagios/templates/estagios/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Gestão de Contratos{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'estagios/css/style.css' %}">
    {% block page_styles %}{% endblock %}
</head>
<body>
    <header class="main-header">
        <div class="container">
            <h1 class="logo">ELLENCO ESTÁGIOS</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'contrato-lista' %}">Gerenciar Contratos</a></li>
                </ul>
            </nav>
            <!--<nav>
                <ul>
                    {% if contrato %}
                        <li><a href="{% url 'contrato-gerar-termo-compromisso' pk=contrato.id %}">Gerar Contrato de Estágio</a></li>
                    {% endif %}
                    {% if rescisao %}
                        <li><a href="{% url 'rescisao-gerar-termo-rescisao' pk=rescisao.id %}">Gerar Termo de Rescisão</a></li>
                    {% endif %}
                </ul>
            </nav>-->
        </div>
    </header>

    <main class="main-content">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <footer class="main-footer">
        <div class="container">
            <p>&copy; {% now "Y" %} ELLENCO ESTÁGIOS. Todos os direitos reservados.</p>
        </div>
    </footer>
</body>
</html>

estagios/templates/estagios/cadastro_recrutamento.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Ficha de Cadastro - Recrutamento</title>
    <style>
        @page {
            margin: 1.5cm;
            @bottom-right {
                content: "Página " counter(page) " de " counter(pages);
                font-size: 9pt;
            }
        }

        body {
            font-family: 'Times New Roman', Times, serif;
            font-size: 10.5pt;
            line-height: 1.3; /* Aumentado para melhor legibilidade */
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        td {
            padding: 1px 3px;
            vertical-align: top;
        }

        .header-logo {
            font-family: Arial, Helvetica, sans-serif;
            font-weight: bold;
            font-size: 14pt;
        }

        .header-main-title {
            text-align: center;
            font-weight: bold;
            font-size: 11pt;
        }

        .header-subtitle {
            text-align: center;
            font-size: 9pt;
            font-weight: bold;
            padding: 20px;
            font-size: 18pt;
            margin-left: 7%;
        }

        /* --- ESTILO MODIFICADO --- */
        .contract-box {
            /* border: 1px solid black; -> REMOVIDO */
            text-align: center;
        }
        .contract-box-title {
            font-size: 8pt;
            font-weight: bold;
            /* border-bottom: 1px solid black; -> REMOVIDO */
            padding: 1px;
        }
        .contract-box-content {
            font-size: 10pt;
            font-weight: bold;
            padding: 2px;
        }

        .centered-text {
            text-align: center;
            font-size: 9pt;
            margin: 10px 0;
        }

        .section-title {
            font-weight: bold;
            font-size: 9pt;
            text-transform: uppercase;
            margin-top: 10px;
            margin-bottom: 2px;
        }

        .info-table {
            width: 100%;
            border-collapse: collapse;
            border-bottom: 1px solid black;
            margin-bottom: 20px; /* ESPAÇAMENTO AUMENTADO */
        }

        .info-table td {
            font-size: 9pt;
            font-weight: bold;
            text-transform: uppercase;
            padding: 2px 0;
            width: 50%;
        }

        .info-table strong {
            font-weight: normal;
            text-transform: none;
        }

        .lowercase {
            text-transform: none !important;
        }

        .conditions-title {
            text-align: left;
            font-weight: bold;
            font-size: 9pt;
            /* border: 1px solid black; -> REMOVIDO */
            /* border-bottom: none; -> REMOVIDO */
            /* padding: 2px; -> REMOVIDO */
            margin-top: 25px; /* ESPAÇAMENTO AUMENTADO */
        }
        .conditions-content {
            text-align: left; /* Alinhamento padrão para o conteúdo */
            font-size: 9pt;
            /* border: 1px solid black; -> REMOVIDO */
            /* padding: 3px; -> REMOVIDO */
            margin-top: 5px;
        }

        /* Estilos específicos para conteúdo que deve ser centralizado ou negrito */
        .conditions-content.centered {
             text-align: left;
        }
        /*.conditions-content.bold {
            font-weight: bold;
        }*/

        .clause {
            font-size: 9pt;
            text-align: justify;
            margin-top: 12px; /* ESPAÇAMENTO AUMENTADO */
        }

        .signature-date {
            text-align: center;
            margin-top: 40px; /* ESPAÇAMENTO AUMENTADO */
            margin-bottom: 30px;
            font-size: 10pt;
        }

        .signature-block {
            text-align: center;
            font-size: 9pt;
        }
        .signature-line {
            border-top: 1px solid black;
            margin: 0 auto 2px auto;
            width: 70%;
        }
        .signature-stamp {
            font-size: 8pt;
        }
        /* --- FIM DAS MODIFICAÇÕES DE ESTILO --- */
    </style>
</head>
<body>

    <table style="margin-bottom: 10px;">
        <tr>
            <td style="width: 25%;" class="header-logo">
                <img src="{{ logo_path }}" alt="Logo da Empresa" style="max-width: 100%; height: auto;">
            </td>
            <td style="width: 50%;">
                <!--<div class="header-main-title">TCE - Termo de COMPROMISSO de ESTÁGIO.</div>-->
                <div class="header-subtitle">Ficha de Cadastro - Recrutamento</div>
            </td>
        </tr>
    </table>

    <div class="section-title">Dados Pessoais</div>
<table class="info-table">
    <tr>
        <td><strong>Nome:</strong> {{ candidato.nome }}</td>
        <td><strong>Sexo:</strong> {{ candidato.sexo }}</td>
    </tr>
    <tr>
        <td><strong>RG:</strong> {{ candidato.rg }}</td>
        <td><strong>CPF:</strong> {{ candidato.cpf }}</td>
    </tr>
    <tr>
        <td><strong>Data de Nascimento:</strong> {{ candidato.data_nascimento }}</td>
        <td><strong>Estado Civil:</strong> {{ candidato.get_estado_civil_display }}</td>
    </tr>
    <tr>
        <td><strong>Tem filhos:</strong> {{ candidato.tem_filhos|yesno:'Sim,Não' }}</td>
        <td><strong>Filhos detalhes:</strong> {{ candidato.filho_detalhes_formatado }}</td>
    </tr>
    <tr>
        <td><strong>Celular:</strong> {{ candidato.celular }}</td>
        <td><strong>Celular 2:</strong> {{ candidato.celular2_formatado }}</td>
    </tr>
    <tr>
        <td><strong>Email:</strong> <span class="lowercase">{{ candidato.email }}</span></td>
        <td><strong>Rede Social:</strong> {{ candidato.rede_social }}</td>
    </tr>
    <tr>
        <td><strong>CEP:</strong> {{ candidato.cep }}</td>
        <td colspan="3"><strong>Endereço:</strong> {{ candidato.endereco }}, <strong>N°:</strong> {{ candidato.numero }}, <strong>Bairro:</strong> {{ candidato.bairro }}</td>
    </tr>
    <tr>
        <td><strong>Complemento:</strong> {{ candidato.complemento }}</td>
        <td><strong>Cidade:</strong> {{ candidato.cidade }}</td>
    </tr>
    <tr>
        <td><strong>Estado:</strong> {{ candidato.estado }}</td>
    </tr>
</table>

    <div class="section-title">Informações Adicionais</div>
    <table class="info-table">
        <tr>
            <td><strong>Fumante:</strong> {{ candidato.fumante|yesno:'Sim,Não' }}</td>
            <td><strong>Habilitação:</strong> {{ candidato.get_habilitacao_display }}</td>
        </tr>

        <tr>
            <td><strong>Religião:</strong> {{ candidato.religiao_formatada }}</td>
            <td><strong>Como conheceu a agência:</strong> {{ candidato.conheceu_agencia }}</td>
        </tr>
    </table>

    <div class="section-title">Formação Acadêmica</div>
    <table class="info-table">
        <tr>
            <td colspan="2"><strong>Escolaridade:</strong> {{ candidato.get_escolaridade_display }}</td>
            <td colspan="2"><strong>Curso:</strong> {{ candidato.curso }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Período:</strong> {{ candidato.get_periodo_display }}</td>
            <td colspan="2"><strong>Série / Semestre:</strong> {{ candidato.get_ano_semestre_display }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Data de Término:</strong> {{ candidato.data_termino }}</td>
            <td colspan="2"><strong>Instituição de Ensino:</strong> {{ candidato.instituicao_ensino }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Vale Transporte:</strong> {{ candidato.get_vale_transporte_display }}</td>
            <td colspan="2"><strong>Curso Extracurricular:</strong> {{ candidato.curso_extracurricular }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Aplicativo Escolar:</strong> {{ candidato.app_escolar }}</td>
        </tr>
    </table>

    <div class="section-title">Informações Profissionais</div>
    <table class="info-table">
        <tr>
            <td colspan="2"><strong>Já trabalhou:</strong> {{ candidato.get_trabalho_display }}</td>
            <td colspan="2"><strong>Disponibilidade para trabalhar no final de semana:</strong>
                {{ candidato.disponibilidade_final_semana|yesno:'Sim,Não' }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Microsoft 365 (Pacote Office):</strong> {{ candidato.get_microsoft_365_display }}</td>
            <td colspan="2"><strong>Experiência Profissional:</strong> {{ candidato.experiencia_profissional }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Área de Interesse:</strong> {{ candidato.area_interesse }}</td>
            <td colspan="2"><strong>Vaga Pretendida:</strong> {{ candidato.vaga_pretendida }}</td>
        </tr>
    </table>

    <div class="section-title">Informações Médicas</div>
    <table class="info-table">
        <tr>
            <td colspan="2"><strong>Medicamento Constante:</strong> {{ candidato.get_usa_medicamento_display }}</td>
            <td colspan="2"><strong>Alergia:</strong> {{ candidato.alergia }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Problema de Saúde:</strong> {{ candidato.get_tem_problema_saude_display }}</td>
            <td colspan="2"><strong>PCD:</strong> {{ candidato.get_pcd_display }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>PCD detalhes:</strong> {{ candidato.pcd_detalhes_formatado }}</td>
        </tr>
    </table>

    <div class="section-title">Informações dos Responsáveis</div>
    <table class="info-table">
        <tr>
            <td colspan="2"><strong>Nome do pai:</strong> {{ candidato.nome_responsavel_formatado }}</td>
            <td colspan="2"><strong>Telefone do pai:</strong> {{ candidato.telefone_responsavel_formatado }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Email do pai:</strong> {{ candidato.email_responsavel_formatado }}</td>
            <td colspan="2"><strong>Nome da mãe:</strong> {{ candidato.nome_responsavel2_formatado }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Telefone da mãe:</strong> {{ candidato.telefone_responsavel2_formatado }}</td>
            <td colspan="2"><strong>Email da mãe:</strong> {{ candidato.email_responsavel2_formatado }}</td>
        </tr>
    </table>
    <div class="section-title">Observações:</div>
    <p>{{ candidato.observacoes }}</p>
</body>
</html>

estagios/templates/estagios/contrato_form.html
{% extends 'estagios/base.html' %}

{% block title %}{% if form.instance.pk %}Editar Contrato{% else %}Adicionar Contrato{% endif %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>{% if form.instance.pk %}Editar Contrato{% else %}Adicionar Novo Contrato{% endif %}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Salvar</button>
        <a href="{% url 'contrato-lista' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}